#if !canImport(ObjectiveC)
import XCTest

extension IPUtilsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IPUtilsTests = [
        ("testSockaddrToString", testSockaddrToString),
    ]
}

extension URLRequestOperationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLRequestOperationTests = [
        ("testFetch404", testFetch404),
        ("testFetchFrostLandConstant", testFetchFrostLandConstant),
        ("testFetchInvalidHost", testFetchInvalidHost),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IPUtilsTests.__allTests__IPUtilsTests),
        testCase(URLRequestOperationTests.__allTests__URLRequestOperationTests),
    ]
}
#endif
